<a href="https://colab.research.google.com/github/nikasvesko/repic/blob/main/0302Nika.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
12

12

In [ ]:
type(12) #integer su svi cijeli brojevi

int

In [ ]:
type(12.5) #decimalni brojevi

float

In [ ]:
type("Nika") #strings su sve riječi

str

In [ ]:
"apple"

'apple'

In [ ]:
True

True

In [ ]:
False

False

In [ ]:
3<5 #boolean, zapravo 0 ili 1

True

dictionaries {} #dodajemo osobu i npr. smjer ili godine, pozovem ime i izbaci se ostalo
list []
tuple ()

In [ ]:
t=[1,2,3]

In [ ]:
type([1,2,3]) #dobivamo što je

list

In [ ]:
t

[1, 2, 3]

In [ ]:
plants = {"apple": "a fruit", "banana": "a herb"}

In [ ]:
type({"apple": "a fruit", "banana": "a herb"})

dict

In [ ]:
plants

{'apple': 'a fruit', 'banana': 'a herb'}

In [ ]:
plants["banana"]

'a herb'

In [ ]:
import pandas as pd

In [ ]:
pd.DataFrame(plants, [0,1]) #indeksiranje je broj objekata tj. varijabli u tom dictionariju, py broji od 0

     apple  banana
0  a fruit  a herb
1  a fruit  a herb

In [ ]:
squares= [1,4,9,16,25]

In [ ]:
type(squares)

list

In [ ]:
squares #brojimo 0,1,2,3,4

[1, 4, 9, 16, 25]

In [ ]:
squares[4]

25

In [ ]:
squares[-2] #u drugu stranu

16

In [ ]:
squares[:]

[1, 4, 9, 16, 25]

In [ ]:
squares[1:] #od 1 na dalje, tj. do kraja

[4, 9, 16, 25]

In [ ]:
squares + [36,49,64,81,100] #dodajem stvari u listu, ali ako opet pozovem squares neće pozvati i nove brojeve

[1, 4, 9, 16, 25, 36, 49, 64, 81, 100]

In [ ]:
sq2= squares + [36,49,64,81,100]

In [ ]:
animals = ["dogs", "cats", "birds"]

In [ ]:
animals[0]

'dogs'

In [ ]:
len(sq2[:5]) #duljina do pola :5

5

In [ ]:
letters = ["a", "b", "c", "d"]

In [ ]:
letters

['a', 'b', 'c', 'd']

In [ ]:
letters[1:2]= [1,2,3,4,5]
letters  #umjesto b ce umetnuti to

['a', 1, 2, 3, 4, 5, 2, 3, 4, 5, 'c', 'd']

In [ ]:
abs(-10)

10

In [ ]:
import operator

In [ ]:
1+3

4

In [ ]:
operator.add(1,3) #ista stvar

4

In [ ]:
operator.sub(1,10) #1-10

-9

In [ ]:
operator.eq(1,10) #jesu li jednaki

False

In [ ]:
print(1)

1

In [ ]:
print("Michael", "is", "helping")

Michael is helping

In [ ]:
print(sq2[2:5])

[9, 16, 25]

In [ ]:
None

In [ ]:
type(None)

NoneType

In [ ]:
#funkcije

In [62]:
def our_function(x):   #naša fju ima arg x
  '''multiplies arg by 2'''
  result = x*2
  return result

In [63]:
our_function(10) #vrati x*2

20

In [65]:
our_function(3.14)

6.28

In [66]:
type(our_function) #biblioteke tako funkc, netko je isprogramirao funkcije

function

In [67]:
import math

In [68]:
def ph(c):
  '''računamo ph iz c'''
  ph_value = -math.log10(c)
  return ph_value

In [71]:
ph(0.001)

3.0

In [72]:
def ph1(c):
  return -math.log10(c)

In [73]:
ph1(0.001)

3.0

In [75]:
def task(x,y):
  '''definicija'''
  print('This is log10 of x', math.log10(x))
  print('This is the log10 of y', math.log10(y))
  new_number = math.log10(x) + math.log(y)
  print('The result is below:')
  return new_number

In [77]:
task(1000,2.73)

This is log10 of x 3.0
This is the log10 of y 0.436162647040756
The result is below:

4.004301609196869

In [78]:
def konv_eur(euro):
  dkk = euro*7,55
  return dkk

In [79]:
konv_eur(100)

(700, 55)

In [80]:
def plus(a,b,c,d):
  suma= a+b+c+d
  return suma

In [81]:
plus(3,4,5,6)

18

In [82]:
plus(3,4) #ne radi jer fale c i d

TypeError: plus() missing 2 required positional arguments: 'c' and 'd'

= i ==
= je jednako
== isto

In [87]:
width = 20
height = 5*90
height, width

(450, 20)

In [88]:
width == 30 #jer smo stavili da je 20

False

In [89]:
width = 30 #promijenit ce se u 30

In [90]:
cp1 = 'Tomo'
cp2 = 'Maria'
cp1, cp2

('Tomo', 'Maria')

In [91]:
width == height

False

In [92]:
width = height

In [93]:
width

450

In [94]:
cp1== cp2

False

In [95]:
cp1 = cp2

In [96]:
cp1 == cp2

True

In [97]:
cp1 != cp2 #jer su iste, s ! naglasavamo da nisu

False

In [98]:
5 is 4

<>:1: SyntaxWarning: "is" with 'int' literal. Did you mean "=="?
<>:1: SyntaxWarning: "is" with 'int' literal. Did you mean "=="?
/tmp/ipython-input-171648558.py:1: SyntaxWarning: "is" with 'int' literal. Did you mean "=="?
  5 is 4

False

In [99]:
5 is 5

<>:1: SyntaxWarning: "is" with 'int' literal. Did you mean "=="?
<>:1: SyntaxWarning: "is" with 'int' literal. Did you mean "=="?
/tmp/ipython-input-1783323536.py:1: SyntaxWarning: "is" with 'int' literal. Did you mean "=="?
  5 is 5

True

In [100]:
width is height

True

In [101]:
width is not height

False

Liste

In [102]:
squares

[1, 4, 9, 16, 25]

In [103]:
squares.append(36) #dodali smo 36

In [104]:
squares

[1, 4, 9, 16, 25, 36]

In [105]:
squarespt2 = squares + [36]
squarespt2

[1, 4, 9, 16, 25, 36, 36]

In [110]:
last_list= squares.copy()
last_list

[1, 4, 9, 16, 25, 36, 10]

In [108]:
squares.append(10)
last_list #last list se definiriao kao prijašnji squares

[1, 4, 9, 16, 25, 36]

In [109]:
squares

[1, 4, 9, 16, 25, 36, 10]

In [111]:
print('Participants in the course were', cp1, 'and', cp2)

Participants in the course were Maria and Maria

In [113]:
squares.insert(2,6)
squares

[1, 4, 6, 6, 9, 16, 25, 36, 10]

In [114]:
print('Participants in the course were %s and %s.'
    %(cp1, cp2))

Participants in the course were Maria and Maria.

In [117]:
sample = 'u552'
conc = 0.016

print('In sample %s we found %s mg/L of drugs' %(sample,conc))

In sample u552 we found 0.016 mg/L of drugs

In [118]:
print(f'In a sample {sample} we found {conc} mg /L of drug.') #za recikliranje printova, promijenimm varijablu pa rerunam print

In a sample u552 we found 0.016 mg /L of drug.

In [119]:
def bmi(w, h):
  bmi = w/h **2
  return bmi

In [120]:
bmi(w=65, h=1.64)

24.167162403331353

In [121]:
bmi(65,1.64) #svejedno je

24.167162403331353

c1*v1=c2*v2

In [123]:
def diluter(c1=0.5, v1=1, v2=2):
  '''dilucije'''
  c2= c1*v1/v2
  return c2

In [124]:
diluter() #mozemo reci ulazne arg prije u fju i poslije, sta ima vise logike

0.25

In [125]:
def do_sth_else(a=1, b=2, c=3):
  return(a,b,c)

In [126]:
do_sth_else()

(1, 2, 3)

for

In [128]:
my_friends = ['Michael', 'Tomo','Maria', 'Peter']

In [129]:
for person in my_friends:
  print(person)

Michael
Tomo
Maria
Peter

In [146]:
def bmi(w, h):
  bmi = w/h **2
  return bmi

In [147]:
weights = [80, 90, 55, 70]
heights = [1.8, 2.0, 1.6, 1.55]

for x, friend in enumerate(my_friends):
  bmi_person = bmi(weights[x], heights[x])

  print(f'{friend} has the bmi of {bmi_person}.')

Michael has the bmi of 24.691358024691358.
Tomo has the bmi of 22.5.
Maria has the bmi of 21.484374999999996.
Peter has the bmi of 29.1363163371488.

In [131]:
for x in squares:
  print('Element is %s' %x)

Element is 1
Element is 4
Element is 6
Element is 6
Element is 9
Element is 16
Element is 25
Element is 36
Element is 10

In [132]:
for number in squares:
  print (number)

1
4
6
6
9
16
25
36
10

In [134]:
course_participants= [cp1, cp2]
course_participants

['Maria', 'Maria']

In [135]:
for name in course_participants:
  print(name)

Maria
Maria

In [136]:
for pos in range(len(course_participants)):
  print(pos)

0
1

In [138]:
for n, element in enumerate(squares):
  print(n, element)

0 1
1 4
2 6
3 6
4 9
5 16
6 25
7 36
8 10

In [139]:
for n in squares:
  sq_root= math.sqrt(n)
  print(sq_root)

1.0
2.0
2.449489742783178
2.449489742783178
3.0
4.0
5.0
6.0
3.1622776601683795

In [140]:
# if else
1<=2

True

In [141]:
if 1 == 1:
  print('yes')

yes

In [142]:
cp1= 'Mila'
cp2= 'Marko'

In [143]:
if cp1 == cp2 :
  print('da')

In [144]:
if cp1 != cp2 :
  print('da')

da

In [145]:
if cp1 == cp2 :
  print('da')
else:
  print('ne')

ne

In [148]:
def check_gender_by_name(name):
  if name[-1]=="a":
    gender = "female"
  elif name[-1]=="o":
    gender = "male"
  else:
    gender = "unknown"
  return gender

In [149]:
check_gender_by_name('Marko')

'male'

In [150]:
def ph(c):
  return -math.log10(c)

In [151]:
ph(0.001)

3.0

In [152]:
def ph_evaluator(c=0.001):
  ''' Ph decision maker'''
  ph_value = ph(c)

  if ph_value < 7:
    decision = 'kiselo'
  else:
    decision = 'lužnato'

  return decision

ph_evaluator()

'kiselo'

In [153]:
conc_list = [0.001, 0.01, 0.1, 1, 10]

In [154]:
def test_if_else(a, b):
  '''
  a, b su argumenti
  return 'a > b' or 'a is not > b'
  '''
  if a > b:
    print(a, ' > ', b)
  else:
    print('%d is not > %d' %(a, b))

In [155]:
help(test_if_else)

Help on function test_if_else in module __main__:

test_if_else(a, b)
    a, b su argumenti
    return 'a > b' or 'a is not > b'

In [156]:
test_if_else(6,2)

6  >  2

In [157]:
def rectangle_area(a,b):
  '''dokumentacija'''
  A = a*b
  if a == b:
    print('kvadrat')
  else:
    print('pravokutnik')
  return A

In [158]:
rectangle_area(2,3)

pravokutnik

6

In [159]:
for letter in [1,2,3]:
  print('broj: ', letter)

broj:  1
broj:  2
broj:  3

In [160]:
import numpy as np
nums1=[1,2,3,4,5]
nums1

[1, 2, 3, 4, 5]

In [161]:
nums2 = np.array(nums1)

In [162]:
type(nums1), type(nums2)

(list, numpy.ndarray)

In [163]:
max(nums1)

5

In [164]:
min(nums1)

1

In [165]:
x1 = np.array([1.3, 0, 2])
x1

array([1.3, 0. , 2. ])

In [166]:
x2 = np.array([1, 0, 2])
x2

array([1, 0, 2])

In [167]:
np.linspace(10, 20, 10, endpoint=False)

array([10., 11., 12., 13., 14., 15., 16., 17., 18., 19.])

In [168]:
nule = np.zeros((5,3))
nule.shape

(5, 3)

In [169]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [170]:
x4 = np.random.random((3,10))

In [171]:
pd.DataFrame(x4)

,0,1,2,3,4,5,6,7,8,9
0,0.865609,0.817712,0.914108,0.098219,0.349342,0.293945,0.474954,0.18364,0.475411,0.773543
1,0.202270,0.045629,0.491284,0.949283,0.605390,0.929178,0.048208,0.49565,0.567752,0.729544
2,0.034124,0.114867,0.652835,0.176260,0.546218,0.150228,0.037124,0.97216,0.603027,0.404375

In [172]:
np.arange(2,20).reshape(2,3,3).T

array([[[ 2, 11],
        [ 5, 14],
        [ 8, 17]],

       [[ 3, 12],
        [ 6, 15],
        [ 9, 18]],

       [[ 4, 13],
        [ 7, 16],
        [10, 19]]])

In [173]:
I = np.eye(3)

In [174]:
A = np.arange(9).reshape(3,3)
A

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [175]:
I = np.eye(3)
I@A

array([[0., 1., 2.],
       [3., 4., 5.],
       [6., 7., 8.]])

In [176]:
A@A

array([[ 15,  18,  21],
       [ 42,  54,  66],
       [ 69,  90, 111]])